# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buhrax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0430\u0442\u044c\u0438 \u0437\u0430\u0442\u0440\u0430\u0442', max_length=250),
        ),
    ]
