# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buhrax', '0003_auto_20160324_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': '\u0414\u0435\u043d\u044c\u0433\u0438', 'verbose_name_plural': '\u0414\u0435\u043d\u044c\u0433\u0438'},
        ),
        migrations.AddField(
            model_name='cash',
            name='cash_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='cash_expense',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buhrax.expense'),
        ),
        migrations.AddField(
            model_name='cash',
            name='cash_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='cash',
            table='buhrax_cash',
        ),
    ]
