# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buhrax', '0005_cash_cash_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash_type',
            field=models.CharField(choices=[('P', '\u041f\u0440\u0438\u0445\u043e\u0434'), ('R', '\u0420\u0430\u0441\u0445\u043e\u0434')], max_length=1),
        ),
    ]
