# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buhrax', '0006_auto_20160324_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='cash_desc',
            field=models.CharField(default='\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043a \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044e \u0441\u0440\u0435\u0434\u0441\u0442\u0432', max_length=200),
        ),
    ]
