# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buhrax', '0007_cash_cash_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='planned_cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_cash_date', models.DateField(default=datetime.date.today)),
                ('planned_cash_repeat', models.CharField(choices=[('W', '\u041d\u0435\u0434\u0435\u043b\u044f'), ('M', '\u041c\u0435\u0441\u044f\u0446'), ('Y', '\u0413\u043e\u0434')], max_length=1)),
                ('plannde_cash_value', models.FloatField(default=0.0)),
                ('planned_cash_desc', models.CharField(default='\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043a \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044e \u0441\u0440\u0435\u0434\u0441\u0442\u0432', max_length=200)),
                ('planned_cash_expense', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buhrax.expense')),
            ],
            options={
                'db_table': 'buhrax_planned_cash',
                'verbose_name': '\u0417\u0430\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0437\u0430\u0442\u0440\u0430\u0442\u044b',
                'verbose_name_plural': '\u0417\u0430\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u0437\u0430\u0442\u0440\u0430\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cash',
            name='cash_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
