# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buhrax', '0008_auto_20160417_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u0438 \u0440\u0430\u0441\u0445\u043e\u0434\u043e\u0432', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438 \u0440\u0430\u0441\u0445\u043e\u0434\u043e\u0432'},
        ),
        migrations.RenameField(
            model_name='planned_cash',
            old_name='plannde_cash_value',
            new_name='planned_cash_value',
        ),
    ]
